# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-15 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import referral_project.users.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180412_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, 'Deactivated'), (1, 'Activated')], default=referral_project.users.fields.ActivatedDeactivatedStatus(0)),
        ),
    ]
