# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-14 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields
import referral_project.users.fields
import referral_project.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('identification', models.CharField(blank=True, max_length=255)),
                ('id_kind', models.IntegerField(choices=[(0, 'Passport'), (1, 'Government ID'), (2, 'Diving License')], default=referral_project.users.fields.IDKind(0))),
            ],
            options={
                'verbose_name': 'KYC',
                'verbose_name_plural': 'KYC',
                'permissions': (('can_view_only', 'View only data'),),
            },
            managers=[
                ('objects', referral_project.users.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_view_only', 'View only data'),), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='identification',
        ),
        migrations.AddField(
            model_name='user',
            name='activation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.KYC'),
        ),
    ]
