# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-16 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180914_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='verification_status',
            field=models.CharField(choices=[('PE', 'Pending'), ('VE', 'Verified'), ('DE', 'Declined')], default='PE', max_length=2),
        ),
    ]
