# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-17 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import referral_project.utils.django.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_kyc_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='verification_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Verified'), (2, 'Declined')], default=referral_project.utils.django.fields.VerifyStatus(0)),
        ),
    ]
