# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-20 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import referral_project.admob_credentials.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admob_credentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admobcredential',
            name='adunittype',
            field=models.IntegerField(choices=[(0, 'Banner'), (1, 'Interstitial'), (2, 'Rewards')], default=referral_project.admob_credentials.fields.AdmobTypeOption(0), verbose_name='Ad unit type'),
        ),
    ]
