# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-13 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='budget',
            new_name='reward',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='budget_currency',
            new_name='reward_currency',
        ),
    ]
