# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-15 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20180413_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
