# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-15 19:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='max_interactions',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum allowed interactions'),
        ),
    ]
