# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-16 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20180415_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='user_ip',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
