# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-16 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskstatus_user_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
