# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-16 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20180413_1849'),
        ('tasks', '0007_taskstatus_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='parent_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.Campaign'),
        ),
    ]
