# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-17 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_auto_20180917_1633'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0009_customtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('interacted', models.BooleanField(default=False)),
                ('user_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('parent_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.Campaign')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_task_status', to='tasks.CustomTask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_interacted_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Task Status',
                'verbose_name_plural': 'Custom Task Statuses',
            },
        ),
    ]
