# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-18 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_customtaskstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtask',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
