# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-19 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_customtask_expired'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customtask',
            options={'verbose_name': 'Custom Task', 'verbose_name_plural': 'Custom Tasks'},
        ),
        migrations.AddField(
            model_name='customtask',
            name='work_proof',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
