# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-19 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import referral_project.utils.django.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20180919_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtask',
            name='action',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Submitted')], default=referral_project.utils.django.fields.SubmitStatus(0)),
        ),
    ]
