# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-16 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20180413_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='max_interactions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
