# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-16 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_auto_20180916_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='enable_for_free_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='enable_for_paid_user',
            field=models.BooleanField(default=False),
        ),
    ]
