# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-17 16:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaign_pre_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='max_interactions',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum allowed interactions'),
            preserve_default=False,
        ),
    ]
