# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-13 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import referral_project.transactions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='action',
            field=models.IntegerField(choices=[(-1, 'Unknown'), (0, 'Deposit'), (1, 'Received'), (2, 'Transfer'), (3, 'Withdraw')], default=referral_project.transactions.fields.Action(-1)),
        ),
    ]
