# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-14 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import referral_project.transactions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20180413_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.IntegerField(choices=[(-1, 'Unknown'), (0, 'Deposit'), (1, 'Reward'), (2, 'Transfer'), (3, 'Withdraw'), (4, 'Referral Bonus')], default=referral_project.transactions.fields.Action(-1)),
        ),
    ]
