# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-14 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_method', '0001_initial'),
        ('transactions', '0004_auto_20180414_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('transactions.transaction',),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_method.PaymentInformation', verbose_name='Payment Information'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction ID'),
        ),
    ]
